---
- hosts: all
  become: true
  vars_files:
    - passwords.yml
  vars:
    debian: "{{ ansible_os_family == 'Debian' }}"
    redhat: "{{ ansible_os_family == 'RedHat' }}"
    ansible_become_pass: "{{ become_pass[inventory_hostname] }}"
  tasks:

    - name: install apache2 and php package
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        update_cache: yes #because it is an option for the apt module
        state: latest
      when:  debian
          #      when: ansible_os_family == "Debian"
          #      when: ansible_distribution in ["Debian", "Ubuntu"]
   
    - name: install httpd pkg
      yum:
        name:
          - httpd
          - php
        update_cache: yes
          #      when: ansible_os_family == "RedHat"
      when: redhat
