# PLAYBOOK 
---
- hosts: all
  become: true
  vars_files:
    - passwords.yml
  vars:
    ansible_become_pass: "{{ become_pass[inventory_hostname] }}"
  tasks:

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
